import { SiteShell } from "@/components/site-shell";

const sections = [
  {
    title: "1. Acceptance of Terms",
    paragraphs: [
      'By accessing or using the Matcha mobile application (the "App"), you agree to be bound by these Terms of Use ("Terms"). If you do not agree, do not use the App.',
      'Matcha is operated by MatchSphere Technologies FZ-LLC, a company registered in Dubai, United Arab Emirates ("MatchSphere", "we", "us", "our").',
    ],
  },
  {
    title: "2. Eligibility",
    paragraphs: [
      "You must be at least 18 years old to use the App. By using the App, you represent and warrant that you meet this age requirement and have the legal capacity to enter into these Terms.",
    ],
  },
  {
    title: "3. Definitions",
    bullets: [
      '"Content" means content you provide through the App (including profile information, photos, and messages) and any app-generated suggestions or recommendations.',
      '"User Content" means content you submit or share through the App (including your profile details, photos, and messages).',
      '"AI Output" means suggestions, recommendations, or other outputs generated by automated features in the App.',
    ],
  },
  {
    title: "4. Account Registration and Security",
    paragraphs: ["To use certain features, you must create an account. You agree to:"],
    bullets: [
      "Provide accurate, current, and complete information",
      "Maintain the security of your account credentials",
      "Promptly update information if it changes",
      "Accept responsibility for all activities under your account",
    ],
    trailingParagraph:
      "You may not share your account credentials or make your account available to others.",
  },
  {
    title: "5. Service Description (MVP / Beta)",
    paragraphs: [
      "Matcha is an AI-powered matchmaking platform designed to help users find connections. Our service may use automated systems to analyze information you provide and suggest compatible matches.",
      "The App may be offered as an MVP/beta release. Features may change, be added, removed, or be temporarily unavailable.",
      "We do not guarantee any specific outcomes, matches, responses, or relationships. The quality of suggestions depends on the accuracy and completeness of information you provide and the behavior of other users.",
    ],
  },
  {
    title: "6. AI Output Disclaimer (Accuracy and No Reliance)",
    paragraphs: [
      "AI Output is generated automatically and may be incomplete, incorrect, misleading, or offensive.",
      "You are responsible for evaluating AI Output and deciding how (or whether) to use it. Do not rely on AI Output as the sole basis for decisions or actions, including decisions about interacting with other users.",
    ],
  },
  {
    title: "7. User Content and Messaging",
    paragraphs: [
      "You are responsible for your User Content and your interactions with other users.",
      "The App may allow you to send messages to other users. Messages you send will be shared with the recipients. You should not share sensitive personal information you do not want others to have.",
      "You represent and warrant that you have all rights, permissions, and licenses needed to submit User Content, including profile photos and any other materials you upload or share.",
    ],
  },
  {
    title: "8. Acceptable Use (User Conduct)",
    paragraphs: ["You agree not to:"],
    bullets: [
      "Provide false or misleading information",
      "Harass, abuse, threaten, or harm other users",
      "Use the App for illegal purposes",
      "Upload or share content that is unlawful, infringing, hateful, or sexually explicit",
      "Attempt to access other users' accounts or data without authorization",
      "Scrape, automatically collect, or programmatically extract data from the App",
      "Circumvent security controls, restrictions, or protective measures",
      "Reverse engineer, decompile, or attempt to discover the source code of the App (except where prohibited by applicable law)",
      "Use automated systems to access the App in a way that disrupts or harms the service",
    ],
  },
  {
    title: "9. Safety and In-Person Interactions",
    paragraphs: [
      "We are not responsible for the conduct of any user, online or offline. Use caution and good judgment when communicating with others and when meeting in person. You are solely responsible for your interactions with other users.",
    ],
  },
  {
    title: "10. Moderation and Enforcement",
    paragraphs: [
      "We may (but are not required to) monitor, review, or remove Content, and we may restrict features, suspend, or terminate accounts if we believe Content or behavior violates these Terms, violates applicable law, or creates risk or harm to users or the App.",
      "You can report accounts or Content through in-app tools (if available) or by contacting support@matchsphere.ai.",
    ],
  },
  {
    title: "11. Third-Party Services",
    paragraphs: [
      "The App may rely on third-party services (for example hosting, analytics, authentication, and AI processing). Third-party services are governed by their own terms and policies, and we are not responsible for third-party services.",
    ],
  },
  {
    title: "12. Content Ownership and License to Operate the App",
    paragraphs: [
      "You retain ownership of your User Content as between you and MatchSphere.",
      "By submitting User Content, you grant MatchSphere a non-exclusive, worldwide, royalty-free license to host, store, reproduce, display, process, and use your User Content for the purpose of operating, providing, maintaining, and improving the App and enforcing these Terms.",
    ],
  },
  {
    title: "13. Intellectual Property",
    paragraphs: [
      "The App, including its design, features, and underlying technology, is owned by MatchSphere and its licensors and is protected by applicable intellectual property laws. You may not copy, modify, distribute, or create derivative works from the App except as expressly permitted by these Terms.",
    ],
  },
  {
    title: "14. Intellectual Property Complaints",
    paragraphs: [
      "If you believe Content on the App infringes your intellectual property rights, contact support@matchsphere.ai with sufficient details for us to identify the material and your claim. We may remove allegedly infringing Content and may terminate repeat infringers where appropriate.",
    ],
  },
  {
    title: "15. Disclaimer",
    paragraphs: [
      'The App is provided "as is" and "as available" without warranties of any kind, to the maximum extent permitted by law. We do not warrant that the App will be uninterrupted, secure, or error-free.',
    ],
  },
  {
    title: "16. Limitation of Liability",
    paragraphs: [
      "To the maximum extent permitted by law, MatchSphere Technologies FZ-LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the App.",
    ],
  },
  {
    title: "17. Termination",
    paragraphs: [
      "We may suspend or terminate your account or access to the App at any time if you violate these Terms, or if we reasonably believe your use creates risk or harm, or if required by law.",
      "You may delete your account at any time through the App settings (if available).",
    ],
  },
  {
    title: "18. Changes to These Terms",
    paragraphs: [
      'We may update these Terms from time to time. We will post the updated Terms and update the "Last Updated" date. For significant changes, we may notify you through the App. Your continued use of the App after changes constitutes acceptance of the updated Terms.',
    ],
  },
  {
    title: "19. Governing Law",
    paragraphs: [
      "These Terms shall be governed by and construed in accordance with the laws of the United Arab Emirates. Any disputes shall be subject to the exclusive jurisdiction of the courts of Dubai.",
    ],
  },
  {
    title: "20. General Terms",
    bullets: [
      "Severability. If any provision of these Terms is held invalid or unenforceable, the remaining provisions remain in effect.",
      "No waiver. Our failure to enforce any provision is not a waiver of our right to enforce it later.",
      "Assignment. We may assign these Terms as part of a merger, acquisition, reorganization, or sale of assets.",
    ],
  },
  {
    title: "21. Contact Us",
    paragraphs: ["If you have questions about these Terms, contact:"],
  },
];

export default function TermsOfUsePage() {
  return (
    <SiteShell title="Terms of Use" subtitle="Last Updated: February 2026">
      <article className="space-y-7 text-slate-700">
        {sections.map((section) => (
          <section key={section.title} className="space-y-3">
            <h2 className="text-xl font-semibold text-slate-900">{section.title}</h2>
            {section.paragraphs?.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
            {section.bullets ? (
              <ul className="list-disc space-y-1 pl-5">
                {section.bullets.map((bullet) => (
                  <li key={bullet}>{bullet}</li>
                ))}
              </ul>
            ) : null}
            {section.trailingParagraph ? <p>{section.trailingParagraph}</p> : null}
          </section>
        ))}
        <section className="space-y-1 text-slate-600">
          <p>MatchSphere Technologies FZ-LLC</p>
          <p>Dubai, United Arab Emirates</p>
          <p>Email: support@matchsphere.ai</p>
        </section>
      </article>
    </SiteShell>
  );
}
